### ISSUE TITLE
Index Skeleton

### ISSUE THREAD

**Issue by SNValadez** [SNValadez/coding-quiz-basics#1]
## Still need full index.html

* Outline it
* Upload it

**Comment by PuneetDabral** [comment]
how can i contribute ...??

**Comment by SNValadez** [comment]
Oop, sorry. Already closed it.

**Comment by PuneetDabral** [comment]
ok can you please help me to .. my first contribution actually i am new in open source ...!!!(also you can give me a good first issue)so i can motivate my self ..
